//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.27 at 04:01:21 AM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://zypherscript.com/soap-ws", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zypherscript.soap_ws;
